// ============================================================
// BhoomiDrishti — Mock Data Engine
// Realistic seed data for all Indian states and project types
// ============================================================

import {
  Project,
  DashboardMetrics,
  StateMetrics,
  SectorMetrics,
  TimelineDataPoint,
  AffectedFamily,
  LandParcel,
  Notification,
  WorkflowStage,
  type ProjectType,
  type ProjectStatus,
} from "@/types";

// --- Indian States with coordinates ---
export const INDIAN_STATES: {
  code: string;
  name: string;
  lat: number;
  lng: number;
}[] = [
  { code: "AP", name: "Andhra Pradesh", lat: 15.9129, lng: 79.7400 },
  { code: "AR", name: "Arunachal Pradesh", lat: 28.2180, lng: 94.7278 },
  { code: "AS", name: "Assam", lat: 26.2006, lng: 92.9376 },
  { code: "BR", name: "Bihar", lat: 25.0961, lng: 85.3131 },
  { code: "CG", name: "Chhattisgarh", lat: 21.2787, lng: 81.8661 },
  { code: "GA", name: "Goa", lat: 15.2993, lng: 74.1240 },
  { code: "GJ", name: "Gujarat", lat: 22.2587, lng: 71.1924 },
  { code: "HR", name: "Haryana", lat: 29.0588, lng: 76.0856 },
  { code: "HP", name: "Himachal Pradesh", lat: 31.1048, lng: 77.1734 },
  { code: "JH", name: "Jharkhand", lat: 23.6102, lng: 85.2799 },
  { code: "KA", name: "Karnataka", lat: 15.3173, lng: 75.7139 },
  { code: "KL", name: "Kerala", lat: 10.8505, lng: 76.2711 },
  { code: "MP", name: "Madhya Pradesh", lat: 22.9734, lng: 78.6569 },
  { code: "MH", name: "Maharashtra", lat: 19.7515, lng: 75.7139 },
  { code: "MN", name: "Manipur", lat: 24.6637, lng: 93.9063 },
  { code: "ML", name: "Meghalaya", lat: 25.4670, lng: 91.3662 },
  { code: "MZ", name: "Mizoram", lat: 23.1645, lng: 92.9376 },
  { code: "NL", name: "Nagaland", lat: 26.1584, lng: 94.5624 },
  { code: "OD", name: "Odisha", lat: 20.9517, lng: 85.0985 },
  { code: "PB", name: "Punjab", lat: 31.1471, lng: 75.3412 },
  { code: "RJ", name: "Rajasthan", lat: 27.0238, lng: 74.2179 },
  { code: "SK", name: "Sikkim", lat: 27.5330, lng: 88.5122 },
  { code: "TN", name: "Tamil Nadu", lat: 11.1271, lng: 78.6569 },
  { code: "TS", name: "Telangana", lat: 18.1124, lng: 79.0193 },
  { code: "TR", name: "Tripura", lat: 23.9408, lng: 91.9882 },
  { code: "UP", name: "Uttar Pradesh", lat: 26.8467, lng: 80.9462 },
  { code: "UK", name: "Uttarakhand", lat: 30.0668, lng: 79.0193 },
  { code: "WB", name: "West Bengal", lat: 22.9868, lng: 87.8550 },
  { code: "JK", name: "Jammu & Kashmir", lat: 33.7782, lng: 76.5762 },
  { code: "LA", name: "Ladakh", lat: 34.1526, lng: 77.5771 },
  { code: "DL", name: "Delhi", lat: 28.7041, lng: 77.1025 },
  { code: "CH", name: "Chandigarh", lat: 30.7333, lng: 76.7794 },
  { code: "AN", name: "Andaman & Nicobar", lat: 11.7401, lng: 92.6586 },
  { code: "DN", name: "Dadra & Nagar Haveli", lat: 20.1809, lng: 73.0169 },
  { code: "LD", name: "Lakshadweep", lat: 10.5667, lng: 72.6417 },
  { code: "PY", name: "Puducherry", lat: 11.9416, lng: 79.8083 },
];

// --- Mock Projects ---
export const MOCK_PROJECTS: Project[] = [
  {
    id: "PRJ-001",
    name: "Mumbai-Nagpur Expressway (Samruddhi Mahamarg) Phase III",
    projectCode: "MH-HWY-2024-001",
    type: "highway",
    status: "compensation_disbursing",
    description: "Land acquisition for the remaining 120 km stretch of the Mumbai-Nagpur Expressway connecting Nashik to Aurangabad bypass",
    lrbName: "Maharashtra State Road Development Corporation",
    lrbType: "State Corporation",
    state: "Maharashtra",
    stateCode: "MH",
    district: "Nashik",
    districtCode: "MH-NSK",
    tehsil: "Sinnar",
    villages: ["Sinnar", "Ghoti", "Ozar", "Dindori", "Niphad"],
    totalAreaRequired: 850.5,
    areaNotified: 780.2,
    areaAcquired: 620.8,
    areaPossessed: 510.3,
    totalAffectedFamilies: 1245,
    displacedFamilies: 380,
    rrCompletedFamilies: 290,
    estimatedCost: 48500,
    compensationAssessed: 42300,
    compensationDisbursed: 35800,
    rrCost: 6200,
    proposalDate: "2023-03-15",
    siaStartDate: "2023-06-01",
    siaCompletionDate: "2023-11-20",
    sec11Date: "2024-02-10",
    sec19Date: "2024-08-15",
    awardDate: "2025-03-01",
    targetCompletionDate: "2026-12-31",
    centerLat: 19.9975,
    centerLng: 73.7898,
  },
  {
    id: "PRJ-002",
    name: "Delhi-Varanasi High Speed Rail Corridor",
    projectCode: "UP-RLY-2024-002",
    type: "railway",
    status: "sec19_declared",
    description: "Land acquisition for 800 km high-speed rail corridor connecting Delhi to Varanasi via Lucknow and Prayagraj",
    lrbName: "National High Speed Rail Corporation Ltd",
    lrbType: "Central PSU",
    state: "Uttar Pradesh",
    stateCode: "UP",
    district: "Lucknow",
    districtCode: "UP-LKO",
    tehsil: "Lucknow",
    villages: ["Kakori", "Malihabad", "Mohanlalganj", "Unnao", "Fatehpur"],
    totalAreaRequired: 2200.0,
    areaNotified: 1850.0,
    areaAcquired: 420.5,
    areaPossessed: 180.0,
    totalAffectedFamilies: 4520,
    displacedFamilies: 1200,
    rrCompletedFamilies: 150,
    estimatedCost: 125000,
    compensationAssessed: 68000,
    compensationDisbursed: 22500,
    rrCost: 18000,
    proposalDate: "2023-01-10",
    siaStartDate: "2023-04-01",
    siaCompletionDate: "2023-09-30",
    sec11Date: "2024-01-15",
    sec19Date: "2025-01-10",
    targetCompletionDate: "2028-03-31",
    centerLat: 26.8467,
    centerLng: 80.9462,
  },
  {
    id: "PRJ-003",
    name: "Ken-Betwa River Interlinking Project",
    projectCode: "MP-IRR-2024-003",
    type: "irrigation",
    status: "sec11_notified",
    description: "Land acquisition for India's first river interlinking project connecting Ken and Betwa rivers in Bundelkhand region",
    lrbName: "Ken-Betwa Link Project Authority",
    lrbType: "Central Authority",
    state: "Madhya Pradesh",
    stateCode: "MP",
    district: "Panna",
    districtCode: "MP-PNA",
    tehsil: "Panna",
    villages: ["Panna", "Ajaygarh", "Pawai", "Shahnagar", "Devendranagar"],
    totalAreaRequired: 9000.0,
    areaNotified: 5500.0,
    areaAcquired: 0,
    areaPossessed: 0,
    totalAffectedFamilies: 8200,
    displacedFamilies: 3500,
    rrCompletedFamilies: 0,
    estimatedCost: 445000,
    compensationAssessed: 0,
    compensationDisbursed: 0,
    rrCost: 52000,
    proposalDate: "2023-08-01",
    siaStartDate: "2023-11-01",
    siaCompletionDate: "2024-04-30",
    sec11Date: "2025-06-15",
    targetCompletionDate: "2030-12-31",
    centerLat: 24.7180,
    centerLng: 80.1858,
  },
  {
    id: "PRJ-004",
    name: "Gujarat Dholera Special Investment Region",
    projectCode: "GJ-IND-2024-004",
    type: "industrial",
    status: "award_completed",
    description: "Land acquisition for Dholera SIR industrial township along Delhi-Mumbai Industrial Corridor",
    lrbName: "Dholera Industrial City Development Ltd",
    lrbType: "SPV",
    state: "Gujarat",
    stateCode: "GJ",
    district: "Ahmedabad",
    districtCode: "GJ-AMD",
    tehsil: "Dholera",
    villages: ["Dholera", "Navagam", "Fedra", "Bhadaj", "Khun"],
    totalAreaRequired: 1450.0,
    areaNotified: 1450.0,
    areaAcquired: 1280.0,
    areaPossessed: 950.5,
    totalAffectedFamilies: 2100,
    displacedFamilies: 620,
    rrCompletedFamilies: 480,
    estimatedCost: 85000,
    compensationAssessed: 78500,
    compensationDisbursed: 72000,
    rrCost: 12500,
    proposalDate: "2022-06-01",
    siaStartDate: "2022-09-15",
    siaCompletionDate: "2023-02-28",
    sec11Date: "2023-06-01",
    sec19Date: "2023-12-15",
    awardDate: "2024-09-30",
    targetCompletionDate: "2027-03-31",
    centerLat: 22.2472,
    centerLng: 72.1892,
  },
  {
    id: "PRJ-005",
    name: "Amaravati Capital City Development",
    projectCode: "AP-URB-2024-005",
    type: "urban_development",
    status: "rr_in_progress",
    description: "Land acquisition for development of new capital city of Andhra Pradesh at Amaravati along Krishna River",
    lrbName: "Andhra Pradesh Capital Region Development Authority",
    lrbType: "State Authority",
    state: "Andhra Pradesh",
    stateCode: "AP",
    district: "Guntur",
    districtCode: "AP-GTR",
    tehsil: "Thullur",
    villages: ["Thullur", "Mandadam", "Velagapudi", "Uddandarayunipalem", "Neerukonda"],
    totalAreaRequired: 3500.0,
    areaNotified: 3200.0,
    areaAcquired: 2800.0,
    areaPossessed: 2100.0,
    totalAffectedFamilies: 5800,
    displacedFamilies: 2200,
    rrCompletedFamilies: 1500,
    estimatedCost: 280000,
    compensationAssessed: 245000,
    compensationDisbursed: 210000,
    rrCost: 35000,
    proposalDate: "2022-01-15",
    siaStartDate: "2022-04-01",
    siaCompletionDate: "2022-09-30",
    sec11Date: "2023-01-01",
    sec19Date: "2023-07-15",
    awardDate: "2024-04-01",
    targetCompletionDate: "2027-12-31",
    centerLat: 16.5062,
    centerLng: 80.6480,
  },
  {
    id: "PRJ-006",
    name: "Rajasthan Solar Energy Park — Bhadla Phase IV",
    projectCode: "RJ-REN-2024-006",
    type: "renewable_energy",
    status: "possession_taken",
    description: "Land acquisition for 1500 MW solar park expansion at Bhadla, Jodhpur — world's largest solar park",
    lrbName: "Rajasthan Renewable Energy Corporation",
    lrbType: "State Corporation",
    state: "Rajasthan",
    stateCode: "RJ",
    district: "Jodhpur",
    districtCode: "RJ-JDH",
    tehsil: "Phalodi",
    villages: ["Bhadla", "Mokal", "Dhawa", "Khichan"],
    totalAreaRequired: 4200.0,
    areaNotified: 4200.0,
    areaAcquired: 4200.0,
    areaPossessed: 4200.0,
    totalAffectedFamilies: 320,
    displacedFamilies: 45,
    rrCompletedFamilies: 45,
    estimatedCost: 18000,
    compensationAssessed: 16800,
    compensationDisbursed: 16800,
    rrCost: 1200,
    proposalDate: "2021-09-01",
    siaStartDate: "2021-12-01",
    siaCompletionDate: "2022-05-15",
    sec11Date: "2022-08-01",
    sec19Date: "2023-02-01",
    awardDate: "2023-10-15",
    possessionDate: "2024-06-01",
    targetCompletionDate: "2025-06-30",
    centerLat: 27.5065,
    centerLng: 71.7161,
  },
  {
    id: "PRJ-007",
    name: "Bengaluru Suburban Rail Phase I",
    projectCode: "KA-RLY-2024-007",
    type: "railway",
    status: "objections_open",
    description: "Land acquisition for 148 km suburban rail network connecting Bengaluru with satellite towns",
    lrbName: "Rail Infrastructure Development Company (K) Ltd",
    lrbType: "Joint Venture SPV",
    state: "Karnataka",
    stateCode: "KA",
    district: "Bengaluru Urban",
    districtCode: "KA-BLR",
    tehsil: "Bengaluru North",
    villages: ["Yelahanka", "Devanahalli", "Nelamangala", "Whitefield", "Kengeri"],
    totalAreaRequired: 380.0,
    areaNotified: 320.0,
    areaAcquired: 0,
    areaPossessed: 0,
    totalAffectedFamilies: 1850,
    displacedFamilies: 520,
    rrCompletedFamilies: 0,
    estimatedCost: 95000,
    compensationAssessed: 0,
    compensationDisbursed: 0,
    rrCost: 8500,
    proposalDate: "2024-01-15",
    siaStartDate: "2024-04-01",
    siaCompletionDate: "2024-09-15",
    sec11Date: "2025-02-01",
    targetCompletionDate: "2029-03-31",
    centerLat: 13.0227,
    centerLng: 77.5977,
  },
  {
    id: "PRJ-008",
    name: "Ganga Expressway — Meerut to Prayagraj",
    projectCode: "UP-HWY-2024-008",
    type: "highway",
    status: "award_in_progress",
    description: "Land acquisition for 594 km Ganga Expressway connecting Meerut to Prayagraj — longest expressway in UP",
    lrbName: "UP Expressways Industrial Development Authority",
    lrbType: "State Authority",
    state: "Uttar Pradesh",
    stateCode: "UP",
    district: "Shahjahanpur",
    districtCode: "UP-SHP",
    tehsil: "Shahjahanpur",
    villages: ["Tilhar", "Jalalabad", "Puwayan", "Nigohi", "Katra"],
    totalAreaRequired: 3600.0,
    areaNotified: 3200.0,
    areaAcquired: 1800.0,
    areaPossessed: 800.0,
    totalAffectedFamilies: 6400,
    displacedFamilies: 1800,
    rrCompletedFamilies: 600,
    estimatedCost: 175000,
    compensationAssessed: 98000,
    compensationDisbursed: 62000,
    rrCost: 22000,
    proposalDate: "2022-10-01",
    siaStartDate: "2023-01-15",
    siaCompletionDate: "2023-07-01",
    sec11Date: "2023-10-15",
    sec19Date: "2024-06-01",
    targetCompletionDate: "2028-06-30",
    centerLat: 27.8974,
    centerLng: 79.9079,
  },
  {
    id: "PRJ-009",
    name: "Paradip-Hyderabad Product Pipeline Expansion",
    projectCode: "OD-IND-2024-009",
    type: "industrial",
    status: "sia_in_progress",
    description: "Land acquisition for petroleum products pipeline expansion from Paradip Refinery to Hyderabad",
    lrbName: "Indian Oil Corporation Ltd",
    lrbType: "Central PSU",
    state: "Odisha",
    stateCode: "OD",
    district: "Jagatsinghpur",
    districtCode: "OD-JSP",
    tehsil: "Paradip",
    villages: ["Paradip", "Kujang", "Ersama", "Balikuda"],
    totalAreaRequired: 520.0,
    areaNotified: 0,
    areaAcquired: 0,
    areaPossessed: 0,
    totalAffectedFamilies: 980,
    displacedFamilies: 0,
    rrCompletedFamilies: 0,
    estimatedCost: 32000,
    compensationAssessed: 0,
    compensationDisbursed: 0,
    rrCost: 4800,
    proposalDate: "2025-01-10",
    siaStartDate: "2025-06-01",
    targetCompletionDate: "2029-12-31",
    centerLat: 20.3165,
    centerLng: 86.6114,
  },
  {
    id: "PRJ-010",
    name: "Tamil Nadu Desalination Plant & Pipeline — Nemmeli III",
    projectCode: "TN-URB-2024-010",
    type: "urban_development",
    status: "expert_review",
    description: "Land acquisition for 400 MLD desalination plant and 85 km distribution pipeline from Nemmeli to Chennai South",
    lrbName: "Chennai Metropolitan Water Supply & Sewerage Board",
    lrbType: "State Board",
    state: "Tamil Nadu",
    stateCode: "TN",
    district: "Kancheepuram",
    districtCode: "TN-KPM",
    tehsil: "Chengalpattu",
    villages: ["Nemmeli", "Sholinganallur", "Muttukadu", "Kovalam"],
    totalAreaRequired: 180.0,
    areaNotified: 0,
    areaAcquired: 0,
    areaPossessed: 0,
    totalAffectedFamilies: 450,
    displacedFamilies: 120,
    rrCompletedFamilies: 0,
    estimatedCost: 28000,
    compensationAssessed: 0,
    compensationDisbursed: 0,
    rrCost: 3500,
    proposalDate: "2025-03-01",
    siaStartDate: "2025-05-15",
    siaCompletionDate: "2025-10-30",
    targetCompletionDate: "2029-06-30",
    centerLat: 12.7866,
    centerLng: 80.2273,
  },
  {
    id: "PRJ-011",
    name: "Zuari Bridge & Highway Widening — NH-66",
    projectCode: "GA-HWY-2024-011",
    type: "highway",
    status: "compensation_disbursing",
    description: "Land acquisition for new 4-lane Zuari bridge and NH-66 widening from Verna to Cortalim in Goa",
    lrbName: "National Highways Authority of India",
    lrbType: "Central Authority",
    state: "Goa",
    stateCode: "GA",
    district: "South Goa",
    districtCode: "GA-SGO",
    tehsil: "Mormugao",
    villages: ["Cortalim", "Agassaim", "Verna", "Chicalim"],
    totalAreaRequired: 85.5,
    areaNotified: 85.5,
    areaAcquired: 72.0,
    areaPossessed: 55.0,
    totalAffectedFamilies: 340,
    displacedFamilies: 95,
    rrCompletedFamilies: 70,
    estimatedCost: 12800,
    compensationAssessed: 11500,
    compensationDisbursed: 9800,
    rrCost: 2100,
    proposalDate: "2023-05-01",
    siaStartDate: "2023-08-01",
    siaCompletionDate: "2024-01-15",
    sec11Date: "2024-04-10",
    sec19Date: "2024-10-01",
    awardDate: "2025-05-15",
    targetCompletionDate: "2027-06-30",
    centerLat: 15.3904,
    centerLng: 73.8790,
  },
  {
    id: "PRJ-012",
    name: "West Bengal Tajpur Deep Sea Port",
    projectCode: "WB-IND-2024-012",
    type: "industrial",
    status: "sia_completed",
    description: "Land acquisition for greenfield deep sea port at Tajpur, Purba Medinipur — strategic port development",
    lrbName: "Tajpur Port Authority",
    lrbType: "State Authority",
    state: "West Bengal",
    stateCode: "WB",
    district: "Purba Medinipur",
    districtCode: "WB-PMD",
    tehsil: "Ramnagar",
    villages: ["Tajpur", "Shankarpur", "Mandarmani", "Junput"],
    totalAreaRequired: 680.0,
    areaNotified: 0,
    areaAcquired: 0,
    areaPossessed: 0,
    totalAffectedFamilies: 1100,
    displacedFamilies: 350,
    rrCompletedFamilies: 0,
    estimatedCost: 55000,
    compensationAssessed: 0,
    compensationDisbursed: 0,
    rrCost: 7500,
    proposalDate: "2024-06-01",
    siaStartDate: "2024-09-01",
    siaCompletionDate: "2025-02-28",
    targetCompletionDate: "2030-12-31",
    centerLat: 21.7625,
    centerLng: 87.4744,
  },
];

// --- Dashboard Metrics ---
export const NATIONAL_METRICS: DashboardMetrics = {
  totalAreaProposed: 26646.0,
  totalAreaNotified: 20587.7,
  totalAreaAcquired: 11193.3,
  totalAreaPossessed: 8795.8,
  totalCompensationAssessed: 560.1,
  totalCompensationDisbursed: 428.9,
  totalCompensationPending: 131.2,
  totalAffectedFamilies: 33305,
  totalDisplacedFamilies: 10830,
  totalRRCompleted: 3135,
  totalProjects: 12,
  projectsOnTrack: 7,
  projectsDelayed: 3,
  projectsCompleted: 2,
  sec11Issued: 9,
  sec19Declared: 7,
  awardsCompleted: 5,
  possessionTaken: 3,
};

// --- State Metrics (Curated 5-State Benchmark for Clear Demonstration) ---
export const STATE_METRICS: StateMetrics[] = [
  { stateCode: "MH", stateName: "Maharashtra", totalProjects: 3, areaAcquired: 2450.5, areaNotified: 3200.0, compensationDisbursed: 85.2, affectedFamilies: 4500, completionPercentage: 76 },
  { stateCode: "GJ", stateName: "Gujarat", totalProjects: 2, areaAcquired: 2100.0, areaNotified: 2800.0, compensationDisbursed: 72.0, affectedFamilies: 3200, completionPercentage: 78 },
  { stateCode: "UP", stateName: "Uttar Pradesh", totalProjects: 3, areaAcquired: 1800.0, areaNotified: 3500.0, compensationDisbursed: 64.5, affectedFamilies: 5800, completionPercentage: 51 },
  { stateCode: "TN", stateName: "Tamil Nadu", totalProjects: 2, areaAcquired: 1420.0, areaNotified: 2100.0, compensationDisbursed: 48.0, affectedFamilies: 2900, completionPercentage: 68 },
  { stateCode: "OD", stateName: "Odisha", totalProjects: 2, areaAcquired: 980.0, areaNotified: 1850.0, compensationDisbursed: 32.5, affectedFamilies: 2100, completionPercentage: 53 },
];

// --- Sector Metrics ---
export const SECTOR_METRICS: SectorMetrics[] = [
  { sector: "highway", label: "National Highway", projectCount: 45, areaAcquired: 8500, compensation: 180.5, families: 12500, color: "#f59e0b" },
  { sector: "railway", label: "Railway", projectCount: 22, areaAcquired: 3200, compensation: 95.0, families: 8200, color: "#3b82f6" },
  { sector: "irrigation", label: "Irrigation", projectCount: 15, areaAcquired: 6800, compensation: 42.0, families: 9800, color: "#06b6d4" },
  { sector: "industrial", label: "Industrial Corridor", projectCount: 18, areaAcquired: 4500, compensation: 85.0, families: 5200, color: "#8b5cf6" },
  { sector: "urban_development", label: "Urban Development", projectCount: 12, areaAcquired: 2100, compensation: 120.0, families: 7800, color: "#ec4899" },
  { sector: "renewable_energy", label: "Renewable Energy", projectCount: 25, areaAcquired: 12000, compensation: 28.0, families: 1500, color: "#22c55e" },
];

// --- Timeline Data (Monthly) ---
export const TIMELINE_DATA: TimelineDataPoint[] = [
  { month: "Jan '25", areaNotified: 1200, areaAcquired: 450, areaPossessed: 280, compensationPaid: 22.5 },
  { month: "Feb '25", areaNotified: 1350, areaAcquired: 520, areaPossessed: 320, compensationPaid: 28.0 },
  { month: "Mar '25", areaNotified: 1580, areaAcquired: 680, areaPossessed: 410, compensationPaid: 35.2 },
  { month: "Apr '25", areaNotified: 1420, areaAcquired: 750, areaPossessed: 480, compensationPaid: 42.0 },
  { month: "May '25", areaNotified: 1650, areaAcquired: 820, areaPossessed: 550, compensationPaid: 48.5 },
  { month: "Jun '25", areaNotified: 1800, areaAcquired: 900, areaPossessed: 620, compensationPaid: 55.0 },
  { month: "Jul '25", areaNotified: 1950, areaAcquired: 1050, areaPossessed: 720, compensationPaid: 62.8 },
  { month: "Aug '25", areaNotified: 2100, areaAcquired: 1180, areaPossessed: 850, compensationPaid: 70.5 },
  { month: "Sep '25", areaNotified: 2250, areaAcquired: 1320, areaPossessed: 980, compensationPaid: 78.0 },
  { month: "Oct '25", areaNotified: 2400, areaAcquired: 1450, areaPossessed: 1100, compensationPaid: 85.2 },
  { month: "Nov '25", areaNotified: 2600, areaAcquired: 1600, areaPossessed: 1250, compensationPaid: 92.0 },
  { month: "Dec '25", areaNotified: 2800, areaAcquired: 1780, areaPossessed: 1400, compensationPaid: 100.5 },
];

// --- Mock Notifications ---
export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: "NOT-001", projectId: "PRJ-001", type: "sec11_preliminary", title: "Preliminary Notification — Mumbai-Nagpur Expressway Phase III", description: "Notification under Section 11 of RFCTLARR Act, 2013 for acquisition of 780.2 hectares in Nashik District", status: "published", issuedDate: "2024-02-10", expiryDate: "2025-02-10", gazetteRef: "GZ/MH/2024/1234" },
  { id: "NOT-002", projectId: "PRJ-001", type: "sec19_declaration", title: "Declaration of Acquisition — Mumbai-Nagpur Expressway Phase III", description: "Declaration under Section 19 for acquisition of land in villages Sinnar, Ghoti, Ozar", status: "published", issuedDate: "2024-08-15", gazetteRef: "GZ/MH/2024/5678" },
  { id: "NOT-003", projectId: "PRJ-002", type: "sec11_preliminary", title: "Preliminary Notification — Delhi-Varanasi HSR Corridor", description: "Notification under Section 11 for 1850 hectares across 5 districts of Uttar Pradesh", status: "published", issuedDate: "2024-01-15", expiryDate: "2025-01-15", gazetteRef: "GZ/UP/2024/0089" },
  { id: "NOT-004", projectId: "PRJ-002", type: "sec19_declaration", title: "Declaration — Delhi-Varanasi HSR Corridor", description: "Declaration under Section 19 for acquisition of land for high-speed rail", status: "published", issuedDate: "2025-01-10", gazetteRef: "GZ/UP/2025/0012" },
  { id: "NOT-005", projectId: "PRJ-003", type: "sec11_preliminary", title: "Preliminary Notification — Ken-Betwa River Interlinking", description: "Notification under Section 11 for 5500 hectares in Panna and Chhatarpur districts", status: "published", issuedDate: "2025-06-15", expiryDate: "2026-06-15", gazetteRef: "GZ/MP/2025/0456" },
  { id: "NOT-006", projectId: "PRJ-004", type: "sec23_award", title: "Award — Dholera SIR Phase I", description: "Collector's Award under Section 23 for 1280 hectares at Dholera Special Investment Region", status: "published", issuedDate: "2024-09-30", gazetteRef: "GZ/GJ/2024/7890" },
  { id: "NOT-007", projectId: "PRJ-007", type: "sec15_objection", title: "Objection Notice — Bengaluru Suburban Rail", description: "Objection filing window open for 60 days from date of Sec 11 notification", status: "published", issuedDate: "2025-02-01", expiryDate: "2025-04-02" },
  { id: "NOT-008", projectId: "PRJ-006", type: "sec38_possession", title: "Possession — Bhadla Solar Park Phase IV", description: "Physical possession taken of 4200 hectares for Bhadla Solar Energy Park expansion", status: "published", issuedDate: "2024-06-01", gazetteRef: "GZ/RJ/2024/3456" },
];

// --- Workflow Stages for a sample project ---
export function getProjectWorkflow(project: Project): WorkflowStage[] {
  const stages: WorkflowStage[] = [
    {
      id: "stage-1",
      name: "Proposal Submission",
      section: "Initial",
      status: project.proposalDate ? "completed" : "upcoming",
      startDate: project.proposalDate,
      completedDate: project.proposalDate,
      description: "Land Requiring Body submits project proposal with DPR",
    },
    {
      id: "stage-2",
      name: "Social Impact Assessment",
      section: "Section 4-6",
      status: project.siaCompletionDate
        ? "completed"
        : project.siaStartDate
        ? "current"
        : "upcoming",
      startDate: project.siaStartDate,
      completedDate: project.siaCompletionDate,
      deadline: project.siaStartDate
        ? new Date(
            new Date(project.siaStartDate).getTime() + 180 * 24 * 60 * 60 * 1000
          ).toISOString().split("T")[0]
        : undefined,
      description: "SIA study conducted with mandatory public hearings in affected areas",
    },
    {
      id: "stage-3",
      name: "Expert Group Appraisal",
      section: "Section 7",
      status: project.status === "expert_review"
        ? "current"
        : project.sec11Date
        ? "completed"
        : "upcoming",
      completedDate: project.sec11Date
        ? new Date(
            new Date(project.sec11Date).getTime() - 60 * 24 * 60 * 60 * 1000
          ).toISOString().split("T")[0]
        : undefined,
      description: "Multi-disciplinary expert group evaluates SIA report findings",
    },
    {
      id: "stage-4",
      name: "Preliminary Notification",
      section: "Section 11",
      status: project.sec11Date ? "completed" : "upcoming",
      completedDate: project.sec11Date,
      description: "Government publishes intent to acquire land in Official Gazette",
    },
    {
      id: "stage-5",
      name: "Objections & Hearing",
      section: "Section 15",
      status: project.status === "objections_open"
        ? "current"
        : project.sec19Date
        ? "completed"
        : "upcoming",
      startDate: project.sec11Date,
      deadline: project.sec11Date
        ? new Date(
            new Date(project.sec11Date).getTime() + 60 * 24 * 60 * 60 * 1000
          ).toISOString().split("T")[0]
        : undefined,
      description: "60-day window for affected persons to file objections",
    },
    {
      id: "stage-6",
      name: "Declaration of Acquisition",
      section: "Section 19",
      status: project.sec19Date ? "completed" : "upcoming",
      completedDate: project.sec19Date,
      description: "Formal declaration of acquisition published with R&R scheme summary",
    },
    {
      id: "stage-7",
      name: "Award by Collector",
      section: "Section 23-30",
      status: project.awardDate
        ? "completed"
        : project.status === "award_in_progress"
        ? "current"
        : "upcoming",
      completedDate: project.awardDate,
      deadline: project.sec19Date
        ? new Date(
            new Date(project.sec19Date).getTime() + 365 * 24 * 60 * 60 * 1000
          ).toISOString().split("T")[0]
        : undefined,
      description: "Collector determines compensation and passes award within 12 months",
    },
    {
      id: "stage-8",
      name: "Compensation Disbursement",
      section: "Section 31-34",
      status: project.status === "compensation_disbursing"
        ? "current"
        : project.possessionDate
        ? "completed"
        : "upcoming",
      description: "Full compensation paid to all affected families within 3 months of award",
    },
    {
      id: "stage-9",
      name: "R&R Implementation",
      section: "Section 31, Schedule II",
      status: project.status === "rr_in_progress"
        ? "current"
        : project.possessionDate
        ? "completed"
        : "upcoming",
      description: "Rehabilitation & Resettlement entitlements provided to affected families",
    },
    {
      id: "stage-10",
      name: "Possession",
      section: "Section 38",
      status: project.possessionDate ? "completed" : "upcoming",
      completedDate: project.possessionDate,
      description: "Physical possession taken after full compensation + R&R completion",
    },
  ];

  return stages;
}

// --- Mock Affected Families (for PRJ-001) ---
export const MOCK_FAMILIES: AffectedFamily[] = [
  { id: "FAM-001", projectId: "PRJ-001", parcelId: "PRC-001", familyHeadName: "Ramesh Patil", fatherHusbandName: "Shankar Patil", familyMembers: 5, category: "obc", isBPL: false, isDisplaced: true, landLost: 2.5, structureLost: true, livelihoods: ["Agriculture", "Dairy"], compensationStatus: "fully_paid", rrStatus: "completed", totalCompensation: 4250000, compensationPaid: 4250000, village: "Sinnar", district: "Nashik", state: "Maharashtra" },
  { id: "FAM-002", projectId: "PRJ-001", parcelId: "PRC-002", familyHeadName: "Suresh Gaikwad", fatherHusbandName: "Mohan Gaikwad", familyMembers: 7, category: "sc", isBPL: true, isDisplaced: true, landLost: 1.2, structureLost: true, livelihoods: ["Agriculture", "Labour"], compensationStatus: "fully_paid", rrStatus: "monetary_paid", totalCompensation: 2800000, compensationPaid: 2800000, village: "Ghoti", district: "Nashik", state: "Maharashtra" },
  { id: "FAM-003", projectId: "PRJ-001", parcelId: "PRC-003", familyHeadName: "Priya Deshmukh", fatherHusbandName: "Vikram Deshmukh", familyMembers: 4, category: "general", isBPL: false, isDisplaced: false, landLost: 3.8, structureLost: false, livelihoods: ["Agriculture", "Horticulture"], compensationStatus: "partially_paid", rrStatus: "plan_approved", totalCompensation: 6500000, compensationPaid: 4200000, village: "Ozar", district: "Nashik", state: "Maharashtra" },
  { id: "FAM-004", projectId: "PRJ-001", parcelId: "PRC-004", familyHeadName: "Akbar Shaikh", fatherHusbandName: "Hamid Shaikh", familyMembers: 6, category: "obc", isBPL: false, isDisplaced: true, landLost: 1.8, structureLost: true, livelihoods: ["Shop Owner", "Agriculture"], compensationStatus: "assessed", rrStatus: "plan_drafted", totalCompensation: 3600000, compensationPaid: 0, village: "Sinnar", district: "Nashik", state: "Maharashtra" },
  { id: "FAM-005", projectId: "PRJ-001", parcelId: "PRC-005", familyHeadName: "Lakshmi Jadhav", fatherHusbandName: "Manoj Jadhav", familyMembers: 3, category: "general", isBPL: false, isDisplaced: false, landLost: 5.2, structureLost: false, livelihoods: ["Agriculture"], compensationStatus: "fully_paid", rrStatus: "not_started", totalCompensation: 8900000, compensationPaid: 8900000, village: "Dindori", district: "Nashik", state: "Maharashtra" },
  { id: "FAM-006", projectId: "PRJ-001", parcelId: "PRC-006", familyHeadName: "Govind More", fatherHusbandName: "Balaji More", familyMembers: 8, category: "st", isBPL: true, isDisplaced: true, landLost: 0.8, structureLost: true, livelihoods: ["Agriculture", "Forest Produce"], compensationStatus: "disputed", rrStatus: "not_started", totalCompensation: 1800000, compensationPaid: 0, village: "Niphad", district: "Nashik", state: "Maharashtra" },
  { id: "FAM-007", projectId: "PRJ-001", parcelId: "PRC-007", familyHeadName: "Anita Sonawane", fatherHusbandName: "Prakash Sonawane", familyMembers: 4, category: "obc", isBPL: false, isDisplaced: false, landLost: 2.0, structureLost: false, livelihoods: ["Agriculture", "Poultry"], compensationStatus: "fully_paid", rrStatus: "completed", totalCompensation: 3400000, compensationPaid: 3400000, village: "Sinnar", district: "Nashik", state: "Maharashtra" },
  { id: "FAM-008", projectId: "PRJ-001", parcelId: "PRC-008", familyHeadName: "Rajendra Kulkarni", fatherHusbandName: "Vasant Kulkarni", familyMembers: 5, category: "general", isBPL: false, isDisplaced: false, landLost: 4.5, structureLost: false, livelihoods: ["Agriculture", "Sugar Cane"], compensationStatus: "partially_paid", rrStatus: "monetary_paid", totalCompensation: 7800000, compensationPaid: 5200000, village: "Ghoti", district: "Nashik", state: "Maharashtra" },
];

// --- Recent Activity Feed ---
export interface ActivityItem {
  id: string;
  type: "notification" | "award" | "compensation" | "possession" | "objection" | "sia";
  title: string;
  project: string;
  state: string;
  timestamp: string;
  icon: string;
}

export const RECENT_ACTIVITIES: ActivityItem[] = [
  { id: "ACT-001", type: "notification", title: "Sec 11 Notification Published", project: "Ken-Betwa River Interlinking", state: "Madhya Pradesh", timestamp: "2025-06-15T10:30:00Z", icon: "📢" },
  { id: "ACT-002", type: "compensation", title: "₹9.8 Cr Compensation Disbursed", project: "Zuari Bridge NH-66", state: "Goa", timestamp: "2025-06-14T14:00:00Z", icon: "💰" },
  { id: "ACT-003", type: "award", title: "Collector's Award Passed", project: "Dholera SIR Phase I", state: "Gujarat", timestamp: "2025-06-13T11:15:00Z", icon: "⚖️" },
  { id: "ACT-004", type: "objection", title: "42 Objections Filed (Sec 15)", project: "Bengaluru Suburban Rail", state: "Karnataka", timestamp: "2025-06-12T09:45:00Z", icon: "📝" },
  { id: "ACT-005", type: "possession", title: "Possession Taken — 4200 ha", project: "Bhadla Solar Park Phase IV", state: "Rajasthan", timestamp: "2025-06-11T16:30:00Z", icon: "🏁" },
  { id: "ACT-006", type: "sia", title: "SIA Study Commenced", project: "Paradip-Hyderabad Pipeline", state: "Odisha", timestamp: "2025-06-10T08:00:00Z", icon: "📋" },
  { id: "ACT-007", type: "compensation", title: "₹35.8 Cr Compensation Disbursed", project: "Mumbai-Nagpur Expressway III", state: "Maharashtra", timestamp: "2025-06-09T12:00:00Z", icon: "💰" },
  { id: "ACT-008", type: "notification", title: "Sec 19 Declaration Published", project: "Delhi-Varanasi HSR Corridor", state: "Uttar Pradesh", timestamp: "2025-06-08T10:00:00Z", icon: "📜" },
];
